-- MySQL Script generated by MySQL Workbench
-- 07/08/21 11:43:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbmessage
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbmessage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbmessage` DEFAULT CHARACTER SET latin1 ;
USE `dbmessage` ;

-- -----------------------------------------------------
-- Table `dbmessage`.`tblmessage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbmessage`.`tblmessage` (
  `mesId` INT(11) NOT NULL AUTO_INCREMENT,
  `mesText` LONGTEXT NULL DEFAULT NULL,
  `mesUser` VARCHAR(255) NULL DEFAULT NULL,
  `mesDate` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`mesId`))
ENGINE = MyISAM
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
